# Generated by Django 6.0 on 2026-01-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='start_date',
        ),
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
