# Generated by Django 6.0 on 2026-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medication_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
