# Generated by Django 6.0 on 2026-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
