# Generated by Django 6.0 on 2026-01-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_dosage_alter_medication_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
