# Generated by Django 6.0 on 2026-06-11 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carerelationship',
            name='caregiver',
            field=models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carerelationship',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doselog',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='medications.medication'),
        ),
        migrations.AddField(
            model_name='doselog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='carerelationship',
            unique_together={('caregiver', 'patient')},
        ),
        migrations.AlterUniqueTogether(
            name='doselog',
            unique_together={('medication', 'scheduled_time')},
        ),
    ]
