# Generated by Django 6.0 on 2026-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('😞', 'Bad'), ('😐', 'Okay'), ('😊', 'Good')], max_length=2)),
                ('note', models.TextField()),
                ('pain_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6)),
                ('tag', models.CharField(default='General', max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
