# Generated by Django 6.0 on 2026-01-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='symptom',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='mood',
            field=models.CharField(choices=[('😞', 'Bad'), ('😐', 'Okay'), ('😊', 'Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='pain_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='tag',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
